### ISSUE TITLE
windows problem

### ISSUE THREAD

**Issue by howlingfreak** [unixpickle/ffmpego#2]
I'm having a problem on my windows machine, I'm not getting an error but the example isn't working.

---
Reading a video example
Decoding a video is similarly straightforward. Simply create a VideoReader and read image.Images from it:

//I changed to ffmpego.NewVideoReader or I got error undefined.
vr, _ := NewVideoReader("input.mp4")

for {
    frame, err := vr.ReadFrame()
    if err == io.EOF {
        break
    }
    // Do something with `frame` here...
   
   // if I  fmt.Println(frame) the result is  nil

}

vr.Close()

---
Then if I open video_reader_test.go & run package tests.
The output:
Running tool: C:\Go\bin\go.exe test -timeout 30s -coverprofile=C:\Users\Owner\AppData\Local\Temp\vscode-goOx62CB\go-code-cover github.com\unixpickle\ffmpego

--- FAIL: TestAudioReader (0.17s)
    C:\Go Programs\go\src\github.com\unixpickle\ffmpego\audio_reader_test.go:45: read |0: file already closed
--- FAIL: TestAudioReaderResampled (0.17s)
    C:\Go Programs\go\src\github.com\unixpickle\ffmpego\audio_reader_test.go:45: read |0: file already closed
--- FAIL: TestAudioWriter (0.06s)
    C:\Go Programs\go\src\github.com\unixpickle\ffmpego\audio_writer_test.go:30: write samples: write |1: file already closed
--- FAIL: TestVideoReader (0.17s)
    C:\Go Programs\go\src\github.com\unixpickle\ffmpego\video_reader_test.go:37: read |0: file already closed
--- FAIL: TestVideoReaderResampled (0.16s)
    C:\Go Programs\go\src\github.com\unixpickle\ffmpego\video_reader_test.go:37: read |0: file already closed
--- FAIL: TestVideoWriter (0.03s)
    C:\Go Programs\go\src\github.com\unixpickle\ffmpego\video_writer_test.go:29: write frame: write |1: file already closed
FAIL
coverage: 77.5% of statements
FAIL	github.com/unixpickle/ffmpego	2.960s

**Comment by unixpickle** [comment]
Hmm, looks like Windows probably doesn't support the way I am creating and passing pipes to subprocesses. It might be possible to work around this with sockets. I'll try to look into this, although I don't have a windows machine to test on (this works on both Linux and macOS)

**Comment by howlingfreak** [comment]
I am fully willing to test possible solutions. :)

**Comment by unixpickle** [comment]
@howlingfreak let me know if it works now. In commit 98a8e1b6d1625e23dd36ddc3c5b2611e828ee5a5 I added a way of communicating with ffmpeg using sockets, which should be supported on windows. I tested that this socket communication method works on Linux, so I'm hopeful it will work on Windows as well.

**Comment by howlingfreak** [comment]
The same fmt.Println(frame) results in:

read video: accept tcp [::]:50576: i/o timeout
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x4f7fce]

goroutine 1 [running, locked to thread]:
github.com/unixpickle/ffmpego.(*VideoReader).ReadFrame(0x0, 0x0, 0x654340, 0xc000180000, 0x1d4c00)
        C:/Go Programs/go/src/github.com/unixpickle/ffmpego/video_reader.go:93 +0x3e
main.main()
        C:/Go Programs/go/src/github.com/Trevor/zNew/main.go:108 +0x485
exit status 2

---

Run package test in video_reader_test.go results in:

Running tool: C:\Go\bin\go.exe test -timeout 30s -coverprofile=C:\Users\Owner\AppData\Local\Temp\vscode-gows3pPg\go-code-cover github.com\unixpickle\ffmpego

--- FAIL: TestAudioReader (10.29s)
    C:\Go Programs\go\src\github.com\unixpickle\ffmpego\audio_reader_test.go:13: read audio: accept tcp [::]:50584: i/o timeout
--- FAIL: TestAudioReaderResampled (10.22s)
    C:\Go Programs\go\src\github.com\unixpickle\ffmpego\audio_reader_test.go:21: read audio: accept tcp [::]:50588: i/o timeout
coverage: 27.0% of statements
panic: test timed out after 30s

goroutine 11 [running]:
testing.(*M).startAlarm.func1()
	C:/Go/src/testing/testing.go:1296 +0x104
created by time.goFunc
	C:/Go/src/time/sleep.go:172 +0x4b

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0000a0c00, 0x59764a, 0xf, 0x5a0790, 0x47a700)
	C:/Go/src/testing/testing.go:879 +0x38a
testing.runTests.func1(0xc0000a0000)
	C:/Go/src/testing/testing.go:1119 +0x7f
testing.tRunner(0xc0000a0000, 0xc000067da0)
	C:/Go/src/testing/testing.go:827 +0xc6
testing.runTests(0xc000004480, 0x6b85e0, 0x8, 0x8, 0x40bef9)
	C:/Go/src/testing/testing.go:1117 +0x2b1
testing.(*M).Run(0xc000094000, 0x0)
	C:/Go/src/testing/testing.go:1034 +0x16c
main.main()
	_testmain.go:116 +0x20c

goroutine 10 [IO wait]:
internal/poll.runtime_pollWait(0x938f80, 0x72, 0x5bad80)
	C:/Go/src/runtime/netpoll.go:173 +0x6d
internal/poll.(*pollDesc).wait(0xc00012e488, 0x72, 0x6a2200, 0x0, 0x0)
	C:/Go/src/internal/poll/fd_poll_runtime.go:85 +0xa1
internal/poll.(*ioSrv).ExecIO(0x6bacd0, 0xc00012e2d8, 0xc000004d60, 0x1, 0x0, 0x190)
	C:/Go/src/internal/poll/fd_windows.go:222 +0x137
internal/poll.(*FD).acceptOne(0xc00012e2c0, 0x190, 0xc00029c0e0, 0x2, 0x2, 0xc00012e2d8, 0xc000148c30, 0xc00028a088, 0x40c7bf, 0x10)
	C:/Go/src/internal/poll/fd_windows.go:796 +0xa9
internal/poll.(*FD).Accept(0xc00012e2c0, 0xc000036910, 0x0, 0x0, 0x0, 0x0, 0xc000000000, 0x0, 0x0, 0x0, ...)
	C:/Go/src/internal/poll/fd_windows.go:830 +0x142
net.(*netFD).accept(0xc00012e2c0, 0x0, 0xc00028a220, 0x52c021)
	C:/Go/src/net/fd_windows.go:193 +0x81
net.(*TCPListener).accept(0xc000006130, 0x6bc160, 0x0, 0x0)
	C:/Go/src/net/tcpsock_posix.go:139 +0x35
net.(*TCPListener).Accept(0xc000006130, 0xbfcada565e500dd4, 0x731daba51, 0x6bc160, 0x0)
	C:/Go/src/net/tcpsock.go:260 +0x4e
github.com/unixpickle/ffmpego.(*ChildSocketStream).Connect(0xc000006138, 0x0, 0x0, 0x0, 0x10)
	C:/Go Programs/go/src/github.com/unixpickle/ffmpego/child_stream.go:154 +0xa8
github.com/unixpickle/ffmpego.newAudioWriter(0xc000135c70, 0x44, 0xac44, 0x2, 0x2, 0xc000135c70)
	C:/Go Programs/go/src/github.com/unixpickle/ffmpego/audio_writer.go:48 +0x1f8
github.com/unixpickle/ffmpego.NewAudioWriter(0xc000135c70, 0x44, 0xac44, 0xc000135c70, 0x44, 0x3c)
	C:/Go Programs/go/src/github.com/unixpickle/ffmpego/audio_writer.go:21 +0x54
github.com/unixpickle/ffmpego.TestAudioWriter(0xc0000a0c00)
	C:/Go Programs/go/src/github.com/unixpickle/ffmpego/audio_writer_test.go:18 +0x1ac
testing.tRunner(0xc0000a0c00, 0x5a0790)
	C:/Go/src/testing/testing.go:827 +0xc6
created by testing.(*T).Run
	C:/Go/src/testing/testing.go:878 +0x363
FAIL	github.com/unixpickle/ffmpego	31.339s

**Comment by unixpickle** [comment]
Huh, this is interesting. It looks like `ffmpeg` is not connecting to the socket. What version of ffmpeg do you have installed? (you can check by running `ffmpeg` with no arguments).

Perhaps we should try taking a look at ffmpeg's standard error output. For example, under [this line](https://github.com/unixpickle/ffmpego/blob/ddb23b67f0a660e3c9c4f6654c09a10cf525c49e/video_reader.go#L66), you could add `cmd.Stderr = os.Stderr` (and add an `os` import to the top of the file). This should make any error messages from ffmpeg print out.

Perhaps ffmpeg on Windows doesn't like ipv6. What happens if you go into `child_stream.go` and replace `"tcp"` with `"tcp4"` on lines 128-132? So try changing:

```go
	addr, err := net.ResolveTCPAddr("tcp", ":0")
	if err != nil {
		return nil, err
	}
	listener, err := net.ListenTCP("tcp", addr)
```

to

```go
	addr, err := net.ResolveTCPAddr("tcp4", ":0")
	if err != nil {
		return nil, err
	}
	listener, err := net.ListenTCP("tcp4", addr)
```

**Comment by howlingfreak** [comment]
I made all the changes, result of running same code:

ffmpeg version git-2020-06-04-7f81785 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200523
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 49.100 / 56. 49.100
  libavcodec     58. 90.100 / 58. 90.100
  libavformat    58. 44.100 / 58. 44.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 84.100 /  7. 84.100
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test-video.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2019-01-27T21:04:47.000000Z
  Duration: 00:19:13.06, start: 0.000000, bitrate: 327 kb/s
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(tv, bt709), 640x360 [SAR 1:1 DAR 16:9], 229 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      creation_time   : 2019-01-27T21:04:47.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 01/27/2019.
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 96 kb/s (default)
    Metadata:
      creation_time   : 2019-01-27T21:04:47.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 01/27/2019.
[tcp @ 00000240a8012dc0] Connection to tcp://0.0.0.0:50746 failed: Error number -138 occurred
tcp://0.0.0.0:50746: Unknown error
read video: accept tcp4 0.0.0.0:50746: i/o timeout
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x4f7ffe]

goroutine 1 [running, locked to thread]:
github.com/unixpickle/ffmpego.(*VideoReader).ReadFrame(0x0, 0x0, 0x654340, 0xc00016c000, 0x1d4c00)
        C:/Go Programs/go/src/github.com/unixpickle/ffmpego/video_reader.go:123 +0x3e
main.main()
        C:/Go Programs/go/src/github.com/Trevor/zNew/main.go:108 +0x485
exit status 2

**Comment by unixpickle** [comment]
Thanks for bearing with me! It seems that ffmpeg is unable to connect to the socket that the Go process is (or claims to be) listening on. 

One possibility is that your firewall is blocking the process from listening on a port. I'm not sure how the windows firewall works and why it wouldn't display some sort of popup for this, but maybe a solution is to change the address from ":0" to "127.0.0.1:0" on line 128 in child_stream.go. This way we aren't listening on a port that other machines could connect to, which is probably a good idea anyway.

**Comment by unixpickle** [comment]
I'm definitely getting the sense from reading [related StackOverflow questions](https://stackoverflow.com/questions/53231849/python-socket-windows-10-connection-times-out/53232787) that Windows 10 will silently block listening on `0.0.0.0` but not on `127.0.0.1`, so I am hopeful that the change I suggested above should fix the problem.

I've already pushed this change to `master`, since even if it doesn't fix the issue, it's a good security fix anyway. In particular, the change (in the master branch) would be to turn

```go
addr, err := net.ResolveTCPAddr("tcp", ":0")
```

into

```go
addr, err := net.ResolveTCPAddr("tcp", "localhost:0")
```

or

```go
addr, err := net.ResolveTCPAddr("tcp", "127.0.0.1:0")
```

**Comment by howlingfreak** [comment]
my test example fmt.Println(frame) works now, the end of the output after ctrl+c :

0 0 0 255 0 0 0 255 0 0 0 2exit status 2
av_interleaved_write_frame(): Unknown error
Error writing trailer of tcp://127.0.0.1:50902: Error number -10054 occurred
frame=    5 fps=nan q=-0.0 Lsize=    3340kB time=00:00:00.16 bitrate=164004.0kbits/s speed=0.00913x    
video:3375kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

**Comment by unixpickle** [comment]
Beautiful, looks like all is working correctly now!

That error from `ffmpeg` is expected (but normally you won't be able to see it). It has to do with `ffmpeg` being unable to send more frames to the go process, since you killed the Go process with Ctrl+C. I'd go back now and remove the `cmd.Stderr = os.Stderr`, as you probably won't need to see the output of `ffmpeg` anymore, and this should hide the error.

**Comment by howlingfreak** [comment]
the output from video_reader_test.go:

Running tool: C:\Go\bin\go.exe test -timeout 30s -coverprofile=C:\Users\Owner\AppData\Local\Temp\vscode-gows3pPg\go-code-cover github.com\unixpickle\ffmpego

ok  	github.com/unixpickle/ffmpego	3.558s	coverage: 71.1% of statements

---

I don't think the tests ever finish, so that could be something.
I'll play around and let you know if I find any other problems

**Comment by unixpickle** [comment]
Huh, that output you posted makes it look like all the tests passed in about 4 seconds. Go should catch any tests that timeout after 30 seconds or so.

**Comment by howlingfreak** [comment]
newbie problem, how do I read audio? ReadSamples in audio_reader.go takes in a []float64, but I don't know what it wants...

**Comment by howlingfreak** [comment]
Maybe found a problem,

vr, err := ffmpego.NewVideoReader("input.mp4")
x := vr.VideoInfo.Width

if I try to access VideoInfo.Width (or .Height) I get an error:

vr.VideoInfo.Width undefined (type func() *ffmpego.VideoInfo has no field or method Width)

**Comment by unixpickle** [comment]
@howlingfreak the VideoInfo error you are reporting is because VideoInfo is a function, not a field, so you want to do `vr.VideoInfo().Width`.

**Comment by unixpickle** [comment]
The audio reader interface is similar to the `io.Reader` interface in Go: you pass a slice, and the `ReadSamples()` function fills audio samples into the slice.

For example, here's an (untested) snippet to read all of the samples from a file:

```go
allSamples := []float64{}
ar, _ := ffmpego.NewAudioReaderResampled("input.wav", 44100)
defer ar.Close()
for {
	buffer := make([]float64, 44100)
	n, err := ar.ReadSamples(buffer)
	allSamples = append(allSamples, buffer[:n]...)
	if err == io.EOF {
		break
	}
}
```

**Comment by unixpickle** [comment]
Going to close this issue since it seems things work on Windows now. Feel free to open new issues as you have questions or find bugs!
