### ISSUE TITLE
audio

### ISSUE THREAD

**Issue by howlingfreak** [unixpickle/ffmpego#3]
Hi, I think audio_read.go is playing the entire test audio file of over 3 minutes, in about 1-2 seconds

---
The example code you provided:

allSamples := []float64{}
ar, _ := ffmpego.NewAudioReaderResampled("input.wav", 44100)
defer ar.Close()
for {
	buffer := make([]float64, 44100)
	n, err := ar.ReadSamples(buffer)
	allSamples = append(allSamples, buffer[:n]...)
	if err == io.EOF {
		break
	}
}

---

I added
cmd.Stderr = os.Stderr
into audio_reader.go, the output:

ffmpeg version git-2020-06-04-7f81785 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200523
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 49.100 / 56. 49.100
  libavcodec     58. 90.100 / 58. 90.100
  libavformat    58. 44.100 / 58. 44.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 84.100 /  7. 84.100
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, matroska,webm, from 'input.mkv':
  Metadata:
    COMPATIBLE_BRANDS: iso6avc1mp41
    MAJOR_BRAND     : dash
    MINOR_VERSION   : 0
    ENCODER         : Lavf58.44.100
  Duration: 00:03:41.04, start: -0.007000, bitrate: 4562 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      HANDLER_NAME    : ISO Media file produced by Google Inc.
      DURATION        : 00:03:41.013000000
    Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
    Metadata:
      DURATION        : 00:03:41.041000000
14400 neurons
Stream mapping:
  Stream #0:1 -> #0:0 (opus (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
3600 neurons
Output #0, s16le, to 'tcp://127.0.0.1:55303':
  Metadata:
    COMPATIBLE_BRANDS: iso6avc1mp41
    MAJOR_BRAND     : dash
    MINOR_VERSION   : 0
    encoder         : Lavf58.44.100
    Stream #0:0(eng): Audio: pcm_s16le, 48000 Hz, mono, s16, 768 kb/s (default)
    Metadata:
      DURATION        : 00:03:41.041000000
      encoder         : Lavc58.90.100 pcm_s16le
900 neurons
16 neurons
size=   20721kB time=00:03:41.02 bitrate= 768.0kbits/s speed=36.6x
video:0kB audio:20721kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%

**Comment by unixpickle** [comment]
What do you mean by "playing"? This code reads samples from the audio file for processing. It will not play any sound over the speakers.

To know if you read the whole file, add `fmt.Println(len(allSamples))` at the end of the code snippet. This should show how many samples have been read. It should be about 8 million samples for a 3 minute audio file at 44100 Hz.

**Comment by howlingfreak** [comment]
It read the whole file 9.7 million samples, is there a way to synchronize audio & video processing?

**Comment by howlingfreak** [comment]
Thank you very much for all your help!

**Comment by unixpickle** [comment]
You will probably need to do a bit of math to figure out how to align frames and audio samples. Let's say there's 44100 samples per second and 30 frames per second. Then at sample n, you can figure out the time via `t = n / 44100`, and you can figure out the nearest frame using `f = round(30*t)`. You could imagine doing this math in reverse as well.
